<h1>Tarea 1: Datos Faltantes</h1>
<p>Jose Luis Romero Vazquez<p>
01/Abril/2023

1. Cargue los datos en Python usando Pandas y muestre los primeros 10 registros

In [ ]:
import pandas as pd
df = pd.read_csv('cervical-cancer_csv.csv')
df.head(10)

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
2,34,1.0,NaN,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.000000,37.0,1.0,3.0,0.0,...,NaN,NaN,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.000000,0.0,1.0,15.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
5,42,3.0,23.0,2.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
6,51,3.0,17.0,6.0,1.0,34.000000,3.4,0.0,0.0,1.0,...,NaN,NaN,0,0,0,0,1,1,0,1
7,26,1.0,26.0,3.0,0.0,0.000000,0.0,1.0,2.0,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
8,45,1.0,20.0,5.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,1,0,1,1,0,0,0,0
9,44,3.0,15.0,NaN,1.0,1.266973,2.8,0.0,0.0,NaN,...,NaN,NaN,0,0,0,0,0,0,0,0

2. Como todas las columnas son numéricas para poder trabajar una columna 
categórica ejecute la siguiente línea:

In [ ]:
df["STDs (number)"]=df["STDs (number)"].replace([0,1,2,3,4],["muy bajo","bajo","medio",
"alto","muy alto"])

In [ ]:
df.head(10)

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
2,34,1.0,NaN,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.000000,37.0,1.0,3.0,0.0,...,NaN,NaN,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.000000,0.0,1.0,15.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
5,42,3.0,23.0,2.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
6,51,3.0,17.0,6.0,1.0,34.000000,3.4,0.0,0.0,1.0,...,NaN,NaN,0,0,0,0,1,1,0,1
7,26,1.0,26.0,3.0,0.0,0.000000,0.0,1.0,2.0,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
8,45,1.0,20.0,5.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,1,0,1,1,0,0,0,0
9,44,3.0,15.0,NaN,1.0,1.266973,2.8,0.0,0.0,NaN,...,NaN,NaN,0,0,0,0,0,0,0,0

In [ ]:
df["STDs (number)"].head(10)

0    muy bajo
1    muy bajo
2    muy bajo
3    muy bajo
4    muy bajo
5    muy bajo
6    muy bajo
7    muy bajo
8    muy bajo
9    muy bajo
Name: STDs (number), dtype: object

In [ ]:
df["STDs (number)"].tail(10)

825    muy bajo
826        bajo
827    muy bajo
828    muy bajo
829    muy bajo
830    muy bajo
831    muy bajo
832    muy bajo
833    muy bajo
834    muy bajo
Name: STDs (number), dtype: object

3.Identifique que porcentaje de valores faltantes tiene cada columna

In [ ]:
df.isna().sum()/len(df)*100

Age                                    0.000000
Number of sexual partners              2.994012
First sexual intercourse               0.838323
Num of pregnancies                     6.706587
Smokes                                 1.556886
Smokes (years)                         1.556886
Smokes (packs/year)                    1.556886
Hormonal Contraceptives               12.335329
Hormonal Contraceptives (years)       12.335329
IUD                                   13.413174
IUD (years)                           13.413174
STDs                                  11.976048
STDs (number)                         11.976048
STDs:condylomatosis                   11.976048
STDs:cervical condylomatosis          11.976048
STDs:vaginal condylomatosis           11.976048
STDs:vulvo-perineal condylomatosis    11.976048
STDs:syphilis                         11.976048
STDs:pelvic inflammatory disease      11.976048
STDs:genital herpes                   11.976048
STDs:molluscum contagiosum            11.976048
STDs:AIDS                             11.976048
STDs:HIV                              11.976048
STDs:Hepatitis B                      11.976048
STDs:HPV                              11.976048
STDs: Number of diagnosis              0.000000
STDs: Time since first diagnosis      91.497006
STDs: Time since last diagnosis       91.497006
Dx:Cancer                              0.000000
Dx:CIN                                 0.000000
Dx:HPV                                 0.000000
Dx                                     0.000000
Hinselmann                             0.000000
Schiller                               0.000000
Citology                               0.000000
Biopsy                                 0.000000
dtype: float64

4. Elimine todos los registros que tienen NaN en la columna 'Smokes'

In [ ]:
df.dropna(subset=['Smokes'],axis=0,inplace=True)

In [ ]:
df.head(50)

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.000000,0.000000,0.0,0.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.000000,0.000000,0.0,0.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
2,34,1.0,NaN,1.0,0.0,0.000000,0.000000,0.0,0.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.000000,37.000000,1.0,3.00,0.0,...,NaN,NaN,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.000000,0.000000,1.0,15.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
5,42,3.0,23.0,2.0,0.0,0.000000,0.000000,0.0,0.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
6,51,3.0,17.0,6.0,1.0,34.000000,3.400000,0.0,0.00,1.0,...,NaN,NaN,0,0,0,0,1,1,0,1
7,26,1.0,26.0,3.0,0.0,0.000000,0.000000,1.0,2.00,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
8,45,1.0,20.0,5.0,0.0,0.000000,0.000000,0.0,0.00,0.0,...,NaN,NaN,1,0,1,1,0,0,0,0
9,44,3.0,15.0,NaN,1.0,1.266973,2.800000,0.0,0.00,NaN,...,NaN,NaN,0,0,0,0,0,0,0,0
10,44,3.0,26.0,4.0,0.0,0.000000,0.000000,1.0,2.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
11,27,1.0,17.0,3.0,0.0,0.000000,0.000000,1.0,8.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
12,45,4.0,14.0,6.0,0.0,0.000000,0.000000,1.0,10.00,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
13,44,2.0,25.0,2.0,0.0,0.000000,0.000000,1.0,5.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
14,43,2.0,18.0,5.0,0.0,0.000000,0.000000,0.0,0.00,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
15,40,3.0,18.0,2.0,0.0,0.000000,0.000000,1.0,15.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
16,41,4.0,21.0,3.0,0.0,0.000000,0.000000,1.0,0.25,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
17,43,3.0,15.0,8.0,0.0,0.000000,0.000000,1.0,3.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
18,42,2.0,20.0,NaN,0.0,0.000000,0.000000,1.0,7.00,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
19,40,2.0,27.0,NaN,0.0,0.000000,0.000000,0.0,0.00,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
20,43,2.0,18.0,4.0,0.0,0.000000,0.000000,1.0,15.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
21,41,3.0,17.0,4.0,0.0,0.000000,0.000000,1.0,10.00,0.0,...,21.0,21.0,0,0,0,0,0,0,0,0
22,40,1.0,18.0,1.0,0.0,0.000000,0.000000,1.0,0.25,0.0,...,2.0,2.0,0,0,0,0,0,1,1,1
23,40,1.0,20.0,2.0,0.0,0.000000,0.000000,1.0,15.00,0.0,...,NaN,NaN,1,0,1,0,1,1,0,1
24,40,3.0,15.0,3.0,0.0,0.000000,0.000000,1.0,3.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
25,44,3.0,19.0,1.0,0.0,0.000000,0.000000,0.0,0.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
26,39,5.0,23.0,2.0,0.0,0.000000,0.000000,0.0,0.00,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
27,39,2.0,17.0,4.0,0.0,0.000000,0.000000,0.0,0.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
28,37,3.0,24.0,1.0,1.0,3.000000,0.040000,0.0,0.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
29,37,6.0,26.0,1.0,0.0,0.000000,0.000000,1.0,0.25,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
30,41,3.0,17.0,3.0,0.0,0.000000,0.000000,1.0,22.00,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
31,40,2.0,21.0,2.0,0.0,0.000000,0.000000,1.0,19.00,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
32,37,3.0,17.0,5.0,1.0,1.266973,0.513202,1.0,10.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
33,37,3.0,15.0,3.0,0.0,0.000000,0.000000,1.0,0.50,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
34,38,2.0,15.0,2.0,0.0,0.000000,0.000000,1.0,0.50,1.0,...,NaN,NaN,0,0,0,0,0,1,0,0
35,37,3.0,17.0,5.0,0.0,0.000000,0.000000,1.0,1.00,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
36,39,2.0,17.0,4.0,0.0,0.000000,0.000000,1.0,1.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
37,37,NaN,18.0,1.0,0.0,0.000000,0.000000,1.0,0.58,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
38,39,1.0,24.0,4.0,0.0,0.000000,0.000000,0.0,0.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
39,36,2.0,20.0,3.0,0.0,0.000000,0.000000,1.0,2.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
40,37,NaN,17.0,5.0,0.0,0.000000,0.000000,0.0,0.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
41,37,2.0,18.0,NaN,0.0,0.000000,0.000000,0.0,0.00,NaN,...,15.0,15.0,0,1,0,1,0,1,0,1
42,36,3.0,18.0,3.0,1.0,1.266973,2.400000,1.0,9.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
43,36,3.0,17.0,3.0,0.0,0.000000,0.000000,0.0,0.00,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
44,37,3.0,19.0,3.0,1.0,12.000000,6.000000,1.0,13.00,0.0,...,NaN,NaN,0,0,0,0,0,1,0,1
45,36,1.0,17.0,4.0,0.0,0.000000,0.000000,1.0,0.25,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
47,40,2.0,20.0,3.0,0.0,0.000000,0.000000,0.0,0.00,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
48,41,2.0,17.0,4.0,0.0,0.000000,0.000000,0.0,0.00,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
49,37,3.0,18.0,3.0,0.0,0.000000,0.000000,1.0,0.25,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
50,36,3.0,15.0,4.0,0.0,0.000000,0.000000,1.0,0.25,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0

5. Verifique si todavía faltan valores para el resto de las columnas

In [ ]:
df.isna().sum()/len(df)*100

Age                                    0.000000
Number of sexual partners              3.041363
First sexual intercourse               0.851582
Num of pregnancies                     6.812652
Smokes                                 0.000000
Smokes (years)                         0.000000
Smokes (packs/year)                    0.000000
Hormonal Contraceptives               11.922141
Hormonal Contraceptives (years)       11.922141
IUD                                   13.138686
IUD (years)                           13.138686
STDs                                  11.800487
STDs (number)                         11.800487
STDs:condylomatosis                   11.800487
STDs:cervical condylomatosis          11.800487
STDs:vaginal condylomatosis           11.800487
STDs:vulvo-perineal condylomatosis    11.800487
STDs:syphilis                         11.800487
STDs:pelvic inflammatory disease      11.800487
STDs:genital herpes                   11.800487
STDs:molluscum contagiosum            11.800487
STDs:AIDS                             11.800487
STDs:HIV                              11.800487
STDs:Hepatitis B                      11.800487
STDs:HPV                              11.800487
STDs: Number of diagnosis              0.000000
STDs: Time since first diagnosis      91.727494
STDs: Time since last diagnosis       91.727494
Dx:Cancer                              0.000000
Dx:CIN                                 0.000000
Dx:HPV                                 0.000000
Dx                                     0.000000
Hinselmann                             0.000000
Schiller                               0.000000
Citology                               0.000000
Biopsy                                 0.000000
dtype: float64

6. Elimine todas las columnas que no tienen al menos el 70% de valores no nulos

In [ ]:
df.dropna(thresh=0.7*len(df),axis=1,inplace=True)

In [ ]:
df

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs:HPV,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0,0,0,0,0,0,0,0,0
2,34,1.0,NaN,1.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.00,0.0,...,0.0,0,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.00,0.0,...,0.0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
830,34,3.0,18.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0,0,0,0,0,0,0,0,0
831,32,2.0,19.0,1.0,0.0,0.0,0.0,1.0,8.00,0.0,...,0.0,0,0,0,0,0,0,0,0,0
832,25,2.0,17.0,0.0,0.0,0.0,0.0,1.0,0.08,0.0,...,0.0,0,0,0,0,0,0,0,1,0
833,33,2.0,24.0,2.0,0.0,0.0,0.0,1.0,0.08,0.0,...,0.0,0,0,0,0,0,0,0,0,0
834,29,2.0,20.0,1.0,0.0,0.0,0.0,1.0,0.50,0.0,...,0.0,0,0,0,0,0,0,0,0,0

7. Verifique el tipo de las columnas

In [ ]:
df.dtypes

Age                                     int64
Number of sexual partners             float64
First sexual intercourse              float64
Num of pregnancies                    float64
Smokes                                float64
Smokes (years)                        float64
Smokes (packs/year)                   float64
Hormonal Contraceptives               float64
Hormonal Contraceptives (years)       float64
IUD                                   float64
IUD (years)                           float64
STDs                                  float64
STDs (number)                          object
STDs:condylomatosis                   float64
STDs:cervical condylomatosis          float64
STDs:vaginal condylomatosis           float64
STDs:vulvo-perineal condylomatosis    float64
STDs:syphilis                         float64
STDs:pelvic inflammatory disease      float64
STDs:genital herpes                   float64
STDs:molluscum contagiosum            float64
STDs:AIDS                             float64
STDs:HIV                              float64
STDs:Hepatitis B                      float64
STDs:HPV                              float64
STDs: Number of diagnosis               int64
Dx:Cancer                               int64
Dx:CIN                                  int64
Dx:HPV                                  int64
Dx                                      int64
Hinselmann                              int64
Schiller                                int64
Citology                                int64
Biopsy                                  int64
dtype: object

8. Remplace los valores faltantes de las columnas numéricas por la media aritmética

In [ ]:
import numpy as np
numeric = df.select_dtypes(include=np.number)
numeric_columns = numeric.columns

In [ ]:
df[numeric_columns] = df[numeric_columns].fillna(df.mean(numeric_only= True))

9. Verifique si todavía faltan valores para el resto de las columnas.

In [ ]:
df.isna().sum()/len(df)*100

Age                                    0.000000
Number of sexual partners              0.000000
First sexual intercourse               0.000000
Num of pregnancies                     0.000000
Smokes                                 0.000000
Smokes (years)                         0.000000
Smokes (packs/year)                    0.000000
Hormonal Contraceptives                0.000000
Hormonal Contraceptives (years)        0.000000
IUD                                    0.000000
IUD (years)                            0.000000
STDs                                   0.000000
STDs (number)                         11.800487
STDs:condylomatosis                    0.000000
STDs:cervical condylomatosis           0.000000
STDs:vaginal condylomatosis            0.000000
STDs:vulvo-perineal condylomatosis     0.000000
STDs:syphilis                          0.000000
STDs:pelvic inflammatory disease       0.000000
STDs:genital herpes                    0.000000
STDs:molluscum contagiosum             0.000000
STDs:AIDS                              0.000000
STDs:HIV                               0.000000
STDs:Hepatitis B                       0.000000
STDs:HPV                               0.000000
STDs: Number of diagnosis              0.000000
Dx:Cancer                              0.000000
Dx:CIN                                 0.000000
Dx:HPV                                 0.000000
Dx                                     0.000000
Hinselmann                             0.000000
Schiller                               0.000000
Citology                               0.000000
Biopsy                                 0.000000
dtype: float64

10.Remplace los valores faltantes de la columna categórica "STDs (number)" por la 
moda de esa columna

In [ ]:
boolean_columns = df.select_dtypes(include=object).columns.tolist()
boolean_columns.remove('STDs (number)')

In [ ]:
#df["steroid"]=df["steroid"].fillna(df["steroid"].mode()[0])
for i in boolean_columns:
    df[i]=df[i].fillna(df[i].mode()[0])

11.Compruebe que ya no queda ningún valor NaN

In [ ]:
df.isna().sum()/len(df)*100

Age                                    0.000000
Number of sexual partners              0.000000
First sexual intercourse               0.000000
Num of pregnancies                     0.000000
Smokes                                 0.000000
Smokes (years)                         0.000000
Smokes (packs/year)                    0.000000
Hormonal Contraceptives                0.000000
Hormonal Contraceptives (years)        0.000000
IUD                                    0.000000
IUD (years)                            0.000000
STDs                                   0.000000
STDs (number)                         11.800487
STDs:condylomatosis                    0.000000
STDs:cervical condylomatosis           0.000000
STDs:vaginal condylomatosis            0.000000
STDs:vulvo-perineal condylomatosis     0.000000
STDs:syphilis                          0.000000
STDs:pelvic inflammatory disease       0.000000
STDs:genital herpes                    0.000000
STDs:molluscum contagiosum             0.000000
STDs:AIDS                              0.000000
STDs:HIV                               0.000000
STDs:Hepatitis B                       0.000000
STDs:HPV                               0.000000
STDs: Number of diagnosis              0.000000
Dx:Cancer                              0.000000
Dx:CIN                                 0.000000
Dx:HPV                                 0.000000
Dx                                     0.000000
Hinselmann                             0.000000
Schiller                               0.000000
Citology                               0.000000
Biopsy                                 0.000000
dtype: float64

12.Vuelva a cargar los datos y realice una interpolación para remplazar los datos 
faltantes de las columnas numéricas

In [ ]:
import pandas as pd
df = pd.read_csv('cervical-cancer_csv.csv')
df.head(10)

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
2,34,1.0,NaN,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.000000,37.0,1.0,3.0,0.0,...,NaN,NaN,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.000000,0.0,1.0,15.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
5,42,3.0,23.0,2.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
6,51,3.0,17.0,6.0,1.0,34.000000,3.4,0.0,0.0,1.0,...,NaN,NaN,0,0,0,0,1,1,0,1
7,26,1.0,26.0,3.0,0.0,0.000000,0.0,1.0,2.0,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
8,45,1.0,20.0,5.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,1,0,1,1,0,0,0,0
9,44,3.0,15.0,NaN,1.0,1.266973,2.8,0.0,0.0,NaN,...,NaN,NaN,0,0,0,0,0,0,0,0

In [ ]:
df.isna().sum()/len(df)*100

Age                                    0.000000
Number of sexual partners              2.994012
First sexual intercourse               0.838323
Num of pregnancies                     6.706587
Smokes                                 1.556886
Smokes (years)                         1.556886
Smokes (packs/year)                    1.556886
Hormonal Contraceptives               12.335329
Hormonal Contraceptives (years)       12.335329
IUD                                   13.413174
IUD (years)                           13.413174
STDs                                  11.976048
STDs (number)                         11.976048
STDs:condylomatosis                   11.976048
STDs:cervical condylomatosis          11.976048
STDs:vaginal condylomatosis           11.976048
STDs:vulvo-perineal condylomatosis    11.976048
STDs:syphilis                         11.976048
STDs:pelvic inflammatory disease      11.976048
STDs:genital herpes                   11.976048
STDs:molluscum contagiosum            11.976048
STDs:AIDS                             11.976048
STDs:HIV                              11.976048
STDs:Hepatitis B                      11.976048
STDs:HPV                              11.976048
STDs: Number of diagnosis              0.000000
STDs: Time since first diagnosis      91.497006
STDs: Time since last diagnosis       91.497006
Dx:Cancer                              0.000000
Dx:CIN                                 0.000000
Dx:HPV                                 0.000000
Dx                                     0.000000
Hinselmann                             0.000000
Schiller                               0.000000
Citology                               0.000000
Biopsy                                 0.000000
dtype: float64

In [ ]:
numeric = df.select_dtypes(include=np.number)
numeric_columns = numeric.columns
df.head(10)

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
2,34,1.0,NaN,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.000000,37.0,1.0,3.0,0.0,...,NaN,NaN,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.000000,0.0,1.0,15.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
5,42,3.0,23.0,2.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
6,51,3.0,17.0,6.0,1.0,34.000000,3.4,0.0,0.0,1.0,...,NaN,NaN,0,0,0,0,1,1,0,1
7,26,1.0,26.0,3.0,0.0,0.000000,0.0,1.0,2.0,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
8,45,1.0,20.0,5.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,1,0,1,1,0,0,0,0
9,44,3.0,15.0,NaN,1.0,1.266973,2.8,0.0,0.0,NaN,...,NaN,NaN,0,0,0,0,0,0,0,0

In [ ]:
df[numeric_columns] = df[numeric_columns].interpolate(method ='linear', limit_direction ='forward')

In [ ]:
df.head(10)

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
2,34,1.0,15.0,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.000000,37.0,1.0,3.0,0.0,...,NaN,NaN,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.000000,0.0,1.0,15.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
5,42,3.0,23.0,2.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
6,51,3.0,17.0,6.0,1.0,34.000000,3.4,0.0,0.0,1.0,...,NaN,NaN,0,0,0,0,1,1,0,1
7,26,1.0,26.0,3.0,0.0,0.000000,0.0,1.0,2.0,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
8,45,1.0,20.0,5.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,1,0,1,1,0,0,0,0
9,44,3.0,15.0,4.5,1.0,1.266973,2.8,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0